<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class TestDataSeeder extends Seeder
{
    public function run(): void
    {
        // Clean up existing test data
        $existingUser = DB::table('users')->where('email', 'test@example.com')->first();
        if ($existingUser) {
            DB::table('activities')->where('user_id', $existingUser->id)->delete();
            DB::table('categories')->where('user_id', $existingUser->id)->delete();
            DB::table('users')->where('id', $existingUser->id)->delete();
        }

        // Create test user
        $userId = DB::table('users')->insertGetId([
            'email' => 'test@example.com',
            'password' => Hash::make('password'),
            'api_token' => bin2hex(random_bytes(32)),
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        // Create categories
        $categories = [
            ['name' => 'Work', 'color' => '#957fb8', 'user_id' => $userId],
            ['name' => 'Personal', 'color' => '#7aa2f7', 'user_id' => $userId],
            ['name' => 'Learning', 'color' => '#9ece6a', 'user_id' => $userId],
            ['name' => 'Health', 'color' => '#f7768e', 'user_id' => $userId],
        ];

        $categoryIds = [];
        foreach ($categories as $category) {
            $categoryIds[] = DB::table('categories')->insertGetId(array_merge($category, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        $position = 0;

        // Backlog tasks
        DB::table('activities')->insert([
            [
                'user_id' => $userId,
                'title' => 'Review pull requests',
                'description' => null,
                'status' => 'backlog',
                'category_id' => $categoryIds[0],
                'deadline' => null,
                'tags' => json_encode(['code-review']),
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => null,
                'position' => $position++,
                'completed_at' => null,
                'reflection_text' => null,
                'time_spent_minutes' => null,
                'category_snapshot_name' => null,
                'category_snapshot_color' => null,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'user_id' => $userId,
                'title' => 'Buy groceries',
                'description' => 'Milk, eggs, bread, vegetables',
                'status' => 'backlog',
                'category_id' => $categoryIds[1],
                'deadline' => now()->addDays(2)->format('Y-m-d'),
                'tags' => json_encode(['shopping', 'urgent']),
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => null,
                'position' => $position++,
                'completed_at' => null,
                'reflection_text' => null,
                'time_spent_minutes' => null,
                'category_snapshot_name' => null,
                'category_snapshot_color' => null,
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'user_id' => $userId,
                'title' => 'Read React documentation',
                'description' => null,
                'status' => 'backlog',
                'category_id' => $categoryIds[2],
                'deadline' => null,
                'tags' => json_encode(['react', 'frontend']),
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => null,
                'position' => $position++,
                'completed_at' => null,
                'reflection_text' => null,
                'time_spent_minutes' => null,
                'category_snapshot_name' => null,
                'category_snapshot_color' => null,
                'created_at' => now()->subDays(7),
                'updated_at' => now()->subDays(7),
            ],
        ]);

        // Today tasks
        DB::table('activities')->insert([
            [
                'user_id' => $userId,
                'title' => 'Morning workout',
                'description' => '30 min cardio + stretching',
                'status' => 'today',
                'category_id' => $categoryIds[3],
                'deadline' => now()->format('Y-m-d 09:00:00'),
                'tags' => json_encode(['fitness', 'routine']),
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => null,
                'position' => $position++,
                'completed_at' => null,
                'reflection_text' => null,
                'time_spent_minutes' => null,
                'category_snapshot_name' => null,
                'category_snapshot_color' => null,
                'created_at' => now()->subDay(),
                'updated_at' => now()->subDay(),
            ],
            [
                'user_id' => $userId,
                'title' => 'Team standup',
                'description' => null,
                'status' => 'today',
                'category_id' => $categoryIds[0],
                'deadline' => now()->format('Y-m-d 10:00:00'),
                'tags' => json_encode(['meeting']),
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => null,
                'position' => $position++,
                'completed_at' => null,
                'reflection_text' => null,
                'time_spent_minutes' => null,
                'category_snapshot_name' => null,
                'category_snapshot_color' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // In process - Project with subtasks
        $projectId = DB::table('activities')->insertGetId([
            'user_id' => $userId,
            'title' => 'Redesign landing page',
            'description' => 'Complete redesign of the main landing page with new branding',
            'status' => 'in_process',
            'category_id' => $categoryIds[0],
            'deadline' => now()->addDays(10)->format('Y-m-d'),
            'tags' => json_encode(['design', 'frontend', 'priority']),
            'is_project' => true,
            'is_on_board' => false,
            'is_quick_capture' => false,
            'parent_id' => null,
            'position' => $position++,
            'completed_at' => null,
            'reflection_text' => null,
            'time_spent_minutes' => null,
            'category_snapshot_name' => null,
            'category_snapshot_color' => null,
            'created_at' => now()->subDays(4),
            'updated_at' => now()->subDays(1),
        ]);

        // Subtasks for the project
        DB::table('activities')->insert([
            [
                'user_id' => $userId,
                'title' => 'Create wireframes',
                'description' => null,
                'status' => 'done',
                'category_id' => $categoryIds[0],
                'deadline' => null,
                'tags' => null,
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => $projectId,
                'position' => 0,
                'completed_at' => now()->subDays(3),
                'reflection_text' => 'Wireframes approved by the team',
                'time_spent_minutes' => 120,
                'category_snapshot_name' => 'Work',
                'category_snapshot_color' => '#957fb8',
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(3),
            ],
            [
                'user_id' => $userId,
                'title' => 'Design hero section',
                'description' => 'New hero with gradient background',
                'status' => 'done',
                'category_id' => $categoryIds[0],
                'deadline' => null,
                'tags' => null,
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => $projectId,
                'position' => 1,
                'completed_at' => now()->subDays(2),
                'reflection_text' => 'Used new color palette, looks great',
                'time_spent_minutes' => 180,
                'category_snapshot_name' => 'Work',
                'category_snapshot_color' => '#957fb8',
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(2),
            ],
            [
                'user_id' => $userId,
                'title' => 'Implement responsive layout',
                'description' => null,
                'status' => 'backlog',
                'category_id' => $categoryIds[0],
                'deadline' => null,
                'tags' => null,
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => $projectId,
                'position' => 2,
                'completed_at' => null,
                'reflection_text' => null,
                'time_spent_minutes' => null,
                'category_snapshot_name' => null,
                'category_snapshot_color' => null,
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(4),
            ],
            [
                'user_id' => $userId,
                'title' => 'Add animations',
                'description' => 'Smooth scroll and fade-in effects',
                'status' => 'backlog',
                'category_id' => $categoryIds[0],
                'deadline' => null,
                'tags' => null,
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => $projectId,
                'position' => 3,
                'completed_at' => null,
                'reflection_text' => null,
                'time_spent_minutes' => null,
                'category_snapshot_name' => null,
                'category_snapshot_color' => null,
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(4),
            ],
        ]);

        // In process - Regular task
        DB::table('activities')->insert([
            'user_id' => $userId,
            'title' => 'Fix authentication bug',
            'description' => 'Users getting logged out randomly',
            'status' => 'in_process',
            'category_id' => $categoryIds[0],
            'deadline' => now()->addDay()->format('Y-m-d'),
            'tags' => json_encode(['bug', 'urgent', 'backend']),
            'is_project' => false,
            'is_on_board' => false,
            'is_quick_capture' => false,
            'parent_id' => null,
            'position' => $position++,
            'completed_at' => null,
            'reflection_text' => null,
            'time_spent_minutes' => null,
            'category_snapshot_name' => null,
            'category_snapshot_color' => null,
            'created_at' => now()->subHours(5),
            'updated_at' => now()->subHours(2),
        ]);

        // Completed project with all subtasks done
        $completedProjectId = DB::table('activities')->insertGetId([
            'user_id' => $userId,
            'title' => 'Setup CI/CD pipeline',
            'description' => 'Automated testing and deployment',
            'status' => 'done',
            'category_id' => $categoryIds[0],
            'deadline' => now()->subDays(5)->format('Y-m-d'),
            'tags' => json_encode(['devops', 'automation']),
            'is_project' => true,
            'is_on_board' => false,
            'is_quick_capture' => false,
            'parent_id' => null,
            'position' => $position++,
            'completed_at' => now()->subDays(1),
            'reflection_text' => 'Pipeline is working great. Deployment time reduced from 30min to 5min. Team is happy with the automation.',
            'time_spent_minutes' => 480,
            'category_snapshot_name' => 'Work',
            'category_snapshot_color' => '#957fb8',
            'created_at' => now()->subDays(10),
            'updated_at' => now()->subDays(1),
        ]);

        DB::table('activities')->insert([
            [
                'user_id' => $userId,
                'title' => 'Configure GitHub Actions',
                'description' => null,
                'status' => 'done',
                'category_id' => $categoryIds[0],
                'deadline' => null,
                'tags' => null,
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => $completedProjectId,
                'position' => 0,
                'completed_at' => now()->subDays(8),
                'reflection_text' => 'Easy setup with yaml config',
                'time_spent_minutes' => 90,
                'category_snapshot_name' => 'Work',
                'category_snapshot_color' => '#957fb8',
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(8),
            ],
            [
                'user_id' => $userId,
                'title' => 'Add test coverage',
                'description' => null,
                'status' => 'done',
                'category_id' => $categoryIds[0],
                'deadline' => null,
                'tags' => null,
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => $completedProjectId,
                'position' => 1,
                'completed_at' => now()->subDays(6),
                'reflection_text' => 'Reached 85% coverage',
                'time_spent_minutes' => 240,
                'category_snapshot_name' => 'Work',
                'category_snapshot_color' => '#957fb8',
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(6),
            ],
            [
                'user_id' => $userId,
                'title' => 'Setup staging environment',
                'description' => null,
                'status' => 'done',
                'category_id' => $categoryIds[0],
                'deadline' => null,
                'tags' => null,
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => $completedProjectId,
                'position' => 2,
                'completed_at' => now()->subDays(3),
                'reflection_text' => null,
                'time_spent_minutes' => 60,
                'category_snapshot_name' => 'Work',
                'category_snapshot_color' => '#957fb8',
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(3),
            ],
            [
                'user_id' => $userId,
                'title' => 'Configure production deployment',
                'description' => null,
                'status' => 'done',
                'category_id' => $categoryIds[0],
                'deadline' => null,
                'tags' => null,
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => $completedProjectId,
                'position' => 3,
                'completed_at' => now()->subDays(1),
                'reflection_text' => 'Smooth deployment with zero downtime',
                'time_spent_minutes' => 90,
                'category_snapshot_name' => 'Work',
                'category_snapshot_color' => '#957fb8',
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(1),
            ],
        ]);

        // More completed tasks
        DB::table('activities')->insert([
            [
                'user_id' => $userId,
                'title' => 'Write blog post about Laravel',
                'description' => 'Tips and tricks for beginners',
                'status' => 'done',
                'category_id' => $categoryIds[2],
                'deadline' => null,
                'tags' => json_encode(['writing', 'laravel', 'tutorial']),
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => null,
                'position' => $position++,
                'completed_at' => now()->subDays(2),
                'reflection_text' => 'Published on Medium. Got 500+ views in first day!',
                'time_spent_minutes' => 150,
                'category_snapshot_name' => 'Learning',
                'category_snapshot_color' => '#9ece6a',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(2),
            ],
            [
                'user_id' => $userId,
                'title' => 'Dentist appointment',
                'description' => null,
                'status' => 'done',
                'category_id' => $categoryIds[3],
                'deadline' => now()->subDays(3)->format('Y-m-d 14:00:00'),
                'tags' => json_encode(['health']),
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => null,
                'position' => $position++,
                'completed_at' => now()->subDays(3),
                'reflection_text' => 'No cavities, all good',
                'time_spent_minutes' => 45,
                'category_snapshot_name' => 'Health',
                'category_snapshot_color' => '#f7768e',
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(3),
            ],
            [
                'user_id' => $userId,
                'title' => 'Complete React course module 3',
                'description' => null,
                'status' => 'done',
                'category_id' => $categoryIds[2],
                'deadline' => null,
                'tags' => json_encode(['react', 'learning']),
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => null,
                'position' => $position++,
                'completed_at' => now()->subDays(4),
                'reflection_text' => 'Hooks are powerful! Need to practice more with useEffect',
                'time_spent_minutes' => 180,
                'category_snapshot_name' => 'Learning',
                'category_snapshot_color' => '#9ece6a',
                'created_at' => now()->subDays(7),
                'updated_at' => now()->subDays(4),
            ],
            [
                'user_id' => $userId,
                'title' => 'Refactor database queries',
                'description' => 'Optimize slow queries in analytics dashboard',
                'status' => 'done',
                'category_id' => $categoryIds[0],
                'deadline' => null,
                'tags' => json_encode(['performance', 'database']),
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => null,
                'position' => $position++,
                'completed_at' => now()->subDays(6),
                'reflection_text' => 'Reduced query time from 3s to 200ms by adding proper indexes',
                'time_spent_minutes' => 120,
                'category_snapshot_name' => 'Work',
                'category_snapshot_color' => '#957fb8',
                'created_at' => now()->subDays(8),
                'updated_at' => now()->subDays(6),
            ],
            [
                'user_id' => $userId,
                'title' => 'Call mom',
                'description' => null,
                'status' => 'done',
                'category_id' => $categoryIds[1],
                'deadline' => null,
                'tags' => json_encode(['family']),
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => null,
                'position' => $position++,
                'completed_at' => now()->subDays(1),
                'reflection_text' => null,
                'time_spent_minutes' => 30,
                'category_snapshot_name' => 'Personal',
                'category_snapshot_color' => '#7aa2f7',
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDays(1),
            ],
        ]);

        // Another project in backlog
        $backlogProjectId = DB::table('activities')->insertGetId([
            'user_id' => $userId,
            'title' => 'Learn Docker',
            'description' => 'Complete Docker course and containerize current projects',
            'status' => 'backlog',
            'category_id' => $categoryIds[2],
            'deadline' => now()->addDays(30)->format('Y-m-d'),
            'tags' => json_encode(['docker', 'devops', 'learning']),
            'is_project' => true,
            'is_on_board' => false,
            'is_quick_capture' => false,
            'parent_id' => null,
            'position' => $position++,
            'completed_at' => null,
            'reflection_text' => null,
            'time_spent_minutes' => null,
            'category_snapshot_name' => null,
            'category_snapshot_color' => null,
            'created_at' => now()->subDays(2),
            'updated_at' => now()->subDays(2),
        ]);

        DB::table('activities')->insert([
            [
                'user_id' => $userId,
                'title' => 'Watch Docker basics videos',
                'description' => null,
                'status' => 'backlog',
                'category_id' => $categoryIds[2],
                'deadline' => null,
                'tags' => null,
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => $backlogProjectId,
                'position' => 0,
                'completed_at' => null,
                'reflection_text' => null,
                'time_spent_minutes' => null,
                'category_snapshot_name' => null,
                'category_snapshot_color' => null,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'user_id' => $userId,
                'title' => 'Create Dockerfile for Laravel app',
                'description' => null,
                'status' => 'backlog',
                'category_id' => $categoryIds[2],
                'deadline' => null,
                'tags' => null,
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => $backlogProjectId,
                'position' => 1,
                'completed_at' => null,
                'reflection_text' => null,
                'time_spent_minutes' => null,
                'category_snapshot_name' => null,
                'category_snapshot_color' => null,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'user_id' => $userId,
                'title' => 'Setup docker-compose',
                'description' => null,
                'status' => 'backlog',
                'category_id' => $categoryIds[2],
                'deadline' => null,
                'tags' => null,
                'is_project' => false,
                'is_on_board' => false,
                'is_quick_capture' => false,
                'parent_id' => $backlogProjectId,
                'position' => 2,
                'completed_at' => null,
                'reflection_text' => null,
                'time_spent_minutes' => null,
                'category_snapshot_name' => null,
                'category_snapshot_color' => null,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
        ]);

        $this->command->info('Test data seeded successfully!');
        $this->command->info('Test user credentials:');
        $this->command->info('Email: test@example.com');
        $this->command->info('Password: password');
    }
}
